const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      description: "High quality Nike Product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 0,
      brand: "Adidas",
      description: "High quality Adidas Product",
    },
    {
      _id: "3",
      name: "Lacoste Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 1000,
      countInStock: 10,
      brand: "Lacoste",
      description: "High class Lacoste product",
    },
    {
      _id: "4",
      name: "Nike Slim Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 110,
      countInStock: 10,
      brand: "Nike",
      description: "High quality Nike Product",
    },
    {
      _id: "5",
      name: "Adidas Cargo Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 170,
      countInStock: 10,
      brand: "Adidas",
      description: "High quality Adidas Product",
    },
    {
      _id: "6",
      name: "Nike Fn Pants",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 50,
      countInStock: 10,
      brand: "Nike",
      description: "High quality Nike Product",
    },
  ],
};

export default data;
